"""Add feedback table

Revision ID: d9048f307462
Revises: fd4efb0b264f
Create Date: 2025-03-13 11:30:26.584971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9048f307462'
down_revision = 'fd4efb0b264f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    with op.batch_alter_table('disease', schema=None) as batch_op:
        batch_op.drop_index('disease_name')

    op.drop_table('disease')
    op.drop_table('prediction')
    op.drop_table('herbal_plant')
    op.drop_table('feedback')
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_index('username')

    op.drop_table('admin')
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('otp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('otp', mysql.VARCHAR(length=6), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('expires_at', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('otp', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('admin',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('role', mysql.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_index('username', ['username'], unique=True)

    op.create_table('feedback',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback_text', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='feedback_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('herbal_plant',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('common_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('scientific_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('botanical_name', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('uses', mysql.TEXT(), nullable=True),
    sa.Column('origin', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('availability', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('climate', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('soil', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('image_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('additional_info', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('prediction',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('prediction_type', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('input_data', mysql.TEXT(), nullable=False),
    sa.Column('result', mysql.TEXT(), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='prediction_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('disease',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('disease_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('description', mysql.TEXT(), nullable=True),
    sa.Column('natural_therapy', mysql.TEXT(), nullable=True),
    sa.Column('yoga_beginner', mysql.TEXT(), nullable=True),
    sa.Column('image_name_beginner', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('yoga_moderate', mysql.TEXT(), nullable=True),
    sa.Column('image_name_moderate', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('yoga_advanced', mysql.TEXT(), nullable=True),
    sa.Column('image_name_advanced', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('disease', schema=None) as batch_op:
        batch_op.create_index('disease_name', ['disease_name'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('action', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.Column('target_user_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], name='audit_log_ibfk_2'),
    sa.ForeignKeyConstraint(['target_user_id'], ['user.id'], name='audit_log_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
